### ISSUE TITLE
Support reading from BQ Views

### ISSUE THREAD

**Issue by pupamanyu** [GoogleCloudPlatform/spark-bigquery-connector#21]
Currently reading from BigQuery Views results in the below exception. Views are used for abstracting the base tables and provide access controls on BigQuery. 

To replicate the issue:

Create a view on BigQuery
Use the view name as Table Name for spark.read operation

Exception:

Exception in thread "main" java.lang.RuntimeException: Table type VIEW is not supported.
        at scala.sys.package$.error(package.scala:27)
        at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelationInternal(BigQueryRelationProvider.scala:55)
        at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:40)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:341)
        at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:239)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:227)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:164)
        at com.google.cloud.spark.bigquery.package$BigQueryDataFrameReader.bigquery(package.scala:24)
        at com.it.bi.etl.ATR_Repurchase$.main(ATR_Repurchase.scala:18)
        at com.it.bi.etl.ATR_Repurchase.main(ATR_Repurchase.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by pmkc** [comment]
You can query the view into a temp table as described in #24 and read from that. Not first class support, but it should work.

**Comment by sergoleksenko** [comment]
@pupamanyu I have the same problem with getting data from BigQuery View in my Java project. Did you solve your problem? And if so, could you please provide your solution?

**Comment by davidrabinowitz** [comment]
Available from 0.10.0-beta
