### ISSUE TITLE
Can not run outside GCP (for example: AWS EMR or on Local)

### ISSUE THREAD

**Issue by achelimed** [GoogleCloudPlatform/spark-bigquery-connector#37]
Hi,

I got this error when running outside GCP.

**Versions used:** `0.6.0-beta` and `0.7.0-beta`

```sh
2019-07-04 09:55:32 INFO  ComputeEngineCredentials:202 - Failed to detect whether we are running on Google Compute Engine.
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.directExecutor()Ljava/util/concurrent/Executor;
        at com.google.api.gax.retrying.BasicRetryingFuture.<init>(BasicRetryingFuture.java:84)
        at com.google.api.gax.retrying.DirectRetryingExecutor.createFuture(DirectRetryingExecutor.java:88)
        at com.google.api.gax.retrying.DirectRetryingExecutor.createFuture(DirectRetryingExecutor.java:74)
        at com.google.cloud.RetryHelper.run(RetryHelper.java:75)
        at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
        at com.google.cloud.bigquery.BigQueryImpl.getTable(BigQueryImpl.java:471)
        at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelationInternal(BigQueryRelationProvider.scala:55)
        at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:37)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:341)
        at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:239)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:227)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:164)
        at com.company.package.MainClass$$anonfun$main$1.apply(Visits.scala:90)
        at com.company.package.MainClass$$anonfun$main$1.apply(Visits.scala:69)
        at scala.Option.foreach(Option.scala:257)
        at com.company.package.MainClass$.main(Visits.scala:69)
        at com.company.package.MainClass.main(Visits.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

```
**My main class looks like:**

```scala
spark.conf.set("credentials", base64String)

val data = spark.read
          .format("bigquery")
          .option("credentials", cred) // set again the cred to be sure
          .option("parentProject", "myProjectId")
          .option("project", myProjectId)
          .option("dataset", myDatasetId)
          .option("table", "myProjectId:myDatasetId.ga_sessions_YYYMMdd")
          .load()
```

**my SBT file looks like:**
```sbt
ThisBuild / scalaVersion := "2.11.11"

lazy val hephaestus = (project in file("."))
  .settings(
    name := appName,
    version := appVersion,
    libraryDependencies ++= Seq(
      "org.apache.spark"       %% "spark-sql"      % "2.3.0" % "provided",
      "com.amazonaws"          % "aws-java-sdk"    % "1.7.4" % "provided",
      "org.apache.hadoop"      % "hadoop-aws"      % "2.7.1" % "provided",
      "com.google.cloud.spark" %% "spark-bigquery" % "0.7.0-beta"
    )
  )

assemblyJarName in assembly := s"$appName-$appVersion.jar"

assemblyShadeRules in assembly := Seq(
  ShadeRule.rename("com.google.guava.**"        -> "repackaged.com.google.guava.@1").inAll,
  ShadeRule.rename("com.google.common.guava.**" -> "repackaged.com.google.common.guava.@1").inAll,
  ShadeRule.rename("com.google.protobuf.**"     -> "repackaged.com.google.protobuf.@1").inAll
)

```

**Deployment on AWS EMR v5.13:**
`export GOOGLE_CLOUD_PROJECT=myProjectId`

```sh
spark-submit \
    --class package.MainClass \
    --master "yarn" \
    --deploy-mode "client" \
    --conf "spark.hadoop.fs.s3a.access.key=********************" \
    --conf "spark.hadoop.fs.s3a.secret.key=*********************" \
    --conf "spark.hadoop.fs.s3a.endpoint=s3.eu-west-1.amazonaws.com" \
    --conf "spark.yarn.appMasterEnv.GOOGLE_CLOUD_PROJECT=myProjectId" \
    application-version.jar
```

**Comment by dboyliao** [comment]
Same issue with `pyspark`.
My python script looks like this:
```
from pyspark.sql import SparkSession

spark = (
    sparkSession.builder
    .appName('myapp')
    .master('local[4]')
    .config('spark.jars', '/path/to/bigquery_spark-bigquery-latest.jar')
    .config('credentialsFile', '/path/to/bigquery_credentials.json')
    .getOrCreate()
)

df = spark.read.format('bigquery').option('table', 'mytable').load()
```

And I get the same missing project id error.

**Comment by xjrk58** [comment]
This [PR](https://github.com/GoogleCloudPlatform/spark-bigquery-connector/pull/33) fixes the problem. You can build custom version with those changes included.

**Comment by suyu-dev** [comment]
Hi @achelimed and @xjrk58 

I'm trying to set up an EMR `emr-5.26.0` cluster and read BigQuery data using Spark.

I use Versions `0.8.1-beta` and seems that works for me directly (I didn't make any changes in the source code here, all I did is just include 0.8.1-beta to my POM file and set environment variables).

When I set up EMR I need to make sure Spark has the environment variable `GOOGLE_CLOUD_PROJECT` as mentioned before in @achelimed 's comment. Instead of `export` it directly in each EC2 instances, I use the `spark-env` and `yarn-env` when configuring the cluster. It seems working fine so far.
```json
[
  {
    "Classification": "spark-env",
    "Properties": {},
    "Configurations": [
      {
        "Classification": "export",
        "Properties": {
          "GOOGLE_CLOUD_PROJECT": "<Your Project ID>"
        },
        "Configurations": []
      }
    ]
  },
  {
    "Classification": "yarn-env",
    "Properties": {},
    "Configurations": [
      {
        "Classification": "export",
        "Properties": {
          "GOOGLE_CLOUD_PROJECT": "<Your Project ID>"
        },
        "Configurations": []
      }
    ]
  }
]
```
Reference: https://stackoverflow.com/questions/45284677/set-environment-variables-in-aws-emr

One problem I was facing was the Google `guava` version conflicts. To resolve that I have to:
1. Add the latest version `28.1-jre` of `guava` to my application POM file (we also use maven shade plugin).
2. Run `spark-submit` like:
```bash
spark-submit \
    --class "<main class>" \
    --master "yarn" \
    --deploy-mode "client" \
    --conf "spark.executor.userClassPathFirst=true" \
    --conf "spark.driver.userClassPathFirst=true" \
    <application jar>
```
Reference: https://github.com/googleapis/google-cloud-java/issues/4414

I just post my solution here just as a reference, it might be different from your use cases, but helpfully it could help.

Regards,

**Comment by davidrabinowitz** [comment]
@achelimed , is it still an issue?
