### ISSUE TITLE
Missing maven dependencies when using --packages and ClassNotFound when using --jars

### ISSUE THREAD

**Issue by juliankeppel** [GoogleCloudPlatform/spark-bigquery-connector#70]
Hi,

I want to play a little bit with the BigQuery connector (on AWS EMR version 5.24.1 with Spark 2.4.2) and run this command: `pyspark --packages com.google.cloud.spark:spark-bigquery_2.11:0.9.1-beta`. But the following three dependencies seem to be missing in maven central:
* javax.jms#jms;1.1!jms.jar
* com.sun.jdmk#jmxtools;1.2.1!jmxtools.jar
* com.sun.jmx#jmxri;1.2.1!jmxri.jar

As a workaround, I tried to download the JAR from here: https://console.cloud.google.com/storage/browser/spark-lib/bigquery and add it to the classpath with this command: `pyspark --jars spark-bigquery-latest.jar`. But when I tried to read a table from BigQuery, I get this error: `ClassNotFoundException: Failed to find data source: com.google.cloud.spark.bigquery`. 

I also tried to use com.google.cloud.spark.bigquery instead of just "bigquery" in format(), without success.

**Comment by davidrabinowitz** [comment]
Can you please send the entire stack trace? Doe sit arrive from the driver or the executors? 
 Please make sure you use an hdfs, gs or s3 location so it can be accessible from the entire cluster.

**Comment by davidrabinowitz** [comment]
Created #72 to handle the --packages issue

**Comment by juliankeppel** [comment]
> 
> 
> The missing jars are related to old Sun licensing issues, nothing we can do about it...
> 
> Can you please send the entire stack trace? Doe sit arrive from the driver or the executors?
> Please make sure you use an hdfs, gs or s3 location so it can be accessible from the entire cluster.

Okay, as I read [here](https://spark.apache.org/docs/latest/submitting-applications.html#advanced-dependency-management), I thought it would be enough to give a local path on the master. But obviosly not for spark-shell or pyspark shell. Now, when I give a s3 path, the error is another one, more library specific: 

`df = spark.read.format("bigquery").option("project", "publicdata").option("table", "publicdata.samples.shakespeare").load()`

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/spark/python/pyspark/sql/readwriter.py", line 172, in load
    return self._df(self._jreader.load())
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/usr/lib/spark/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o175.load.
: java.util.ServiceConfigurationError: org.apache.spark.sql.sources.DataSourceRegister: Provider com.google.cloud.spark.bigquery.BigQueryRelationProvider could not be instantiated
        at java.util.ServiceLoader.fail(ServiceLoader.java:232)
        at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
        at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
        at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:43)
        at scala.collection.Iterator$class.foreach(Iterator.scala:891)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:247)
        at scala.collection.TraversableLike$class.filter(TraversableLike.scala:259)
        at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
        at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:630)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:194)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:167)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: A project ID is required for this service but could not be determined from the builder or the environment.  Please set a project ID using the builder.
        at com.google.cloud.spark.bigquery.repackaged.com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
        at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.ServiceOptions.<init>(ServiceOptions.java:285)
        at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryOptions.<init>(BigQueryOptions.java:91)
        at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryOptions.<init>(BigQueryOptions.java:30)
        at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryOptions$Builder.build(BigQueryOptions.java:86)
        at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryOptions.getDefaultInstance(BigQueryOptions.java:159)
        at com.google.cloud.spark.bigquery.BigQueryRelationProvider$.$lessinit$greater$default$2(BigQueryRelationProvider.scala:29)
        at com.google.cloud.spark.bigquery.BigQueryRelationProvider.<init>(BigQueryRelationProvider.scala:40)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
        ... 24 more
```

**Comment by davidrabinowitz** [comment]
Please note that the full table notation has a colon (':') between the project name and the dataset name. Also if you mention the table's project in the `table` property, you do not need to add an additional `project` property. 

The error itself means that the project the query is running with is not set, probably since it was not set for your credentials. You can set it in the query in the following manner:
`spark.read.format("bigquery").option("table", "publicdata:samples.shakespeare").option("parentProject", "<your-project-id>").load()` 

See more at the connector's [supported properties](https://github.com/GoogleCloudPlatform/spark-bigquery-connector#properties) description.

**Comment by juliankeppel** [comment]
Maybe you should note in your README, that the connector uses legacy SQL. Because in the standard SQL syntax for BigQuery, you address your table with `<project>.<dataset>.<table>`. See also: https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax?hl=de#syntax

I tried different variations of `parentProject`, project in the `table` property and in the separate `project` property. I'm not able to get it work. I always get the same error message (the one already pasted above).

**Comment by davidrabinowitz** [comment]
The table name is [parsed by the connector](https://github.com/GoogleCloudPlatform/spark-bigquery-connector/blob/0.9.1-beta/src/main/scala/com/google/cloud/spark/bigquery/BigQueryUtil.scala#L50), so both `table:dataset.table` and `table.dataset.table` formats are supported.

Usually the project id is taken from the credentials if the project is not running in the GCP. Is the credentials file belong to  personal account or service account? Can you please use it with the gcloud CLI to make sure it's ok?

Another question - does the credentials file exist on the spark's driver server? It is usually one of the worker nodes, not the cluster master.

**Comment by juliankeppel** [comment]
Okay, now it works with: 
```
pyspark \     
    --files <path-to-credential-file> \
    --conf spark.executorEnv.GOOGLE_APPLICATION_CREDENTIALS=<name-of-credential-file> \
    --conf spark.yarn.appMasterEnv.GOOGLE_APPLICATION_CREDENTIALS=<name-of-credential-file> \
    --jars <path-to-bigquery-lib-jar> \
```

**Comment by vliao-semios** [comment]
I came across similar issue when working in Jupyter on Dataproc.

I created cluster using following cmd:

```
 gcloud beta dataproc clusters create test-cluster \                                                                                                                                                                                          
     --project $MY_PROJECT_NAME \                                                                                                                                                                                                    
     --enable-component-gateway \                                                                                                                                                                                                             
     --optional-components=ANACONDA,JUPYTER \                                                                                                                                                                                                 
     --metadata 'PIP_PACKAGES=requests_oauthlib google-cloud-bigquery' \                                                                                                                                                                      
     --metadata gcs-connector-version=1.9.16 \                                                                                                                                                                                                
     --metadata bigquery-connector-version=0.13.16 \                                                                                                                                                                                          
     --bucket $MY_JUPYTER_BUCKET \                                                                                                                                                                                                
     --region $MY_REGION \                                                                                                                                                                                                                      
     --initialization-actions=gs://dataproc-initialization-actions/python/pip-install.sh,gs://dataproc-initialization-actions/connectors/connectors.sh \                                                                                      
     --single-node
```

And my code failed to find the connector class:

```
words = spark.read.format('bigquery') \                                                                                                                                                                                                      
   .option('table', 'bigquery-public-data:samples.shakespeare') \                                                                                                                                                                             
   .load()                                                                                                                                                                                                                                    
 words.createOrReplaceTempView('words')                                                                                                                                                                                                       
```

And got exception:


```
Py4JJavaErrorTraceback (most recent call last)
<ipython-input-3-044c8df53274> in <module>()
----> 1 words = spark.read.format('bigquery')   .option('table', 'semios-vliao-test-project:dev_imagery_analysis.dev_jobs')   .load()

/usr/lib/spark/python/pyspark/sql/readwriter.py in load(self, path, format, schema, **options)
    170             return self._df(self._jreader.load(self._spark._sc._jvm.PythonUtils.toSeq(path)))
    171         else:
--> 172             return self._df(self._jreader.load())
    173 
    174     @since(1.4)

/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/usr/lib/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/usr/lib/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o67.load.
: java.lang.ClassNotFoundException: Failed to find data source: bigquery. Please find packages at http://spark.apache.org/third-party-projects.html
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:639)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:190)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: bigquery.DefaultSource
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$23$$anonfun$apply$15.apply(DataSource.scala:622)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$23$$anonfun$apply$15.apply(DataSource.scala:622)
	at scala.util.Try$.apply(Try.scala:192)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$23.apply(DataSource.scala:622)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$23.apply(DataSource.scala:622)
	at scala.util.Try.orElse(Try.scala:84)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:622)
	... 13 more

```

I checked the Spark cluster creation log, the init script runs well, the bigquery connector get's downloaded and linked by:

```

**Comment by davidrabinowitz** [comment]
This init script downloads the hadoop connector, not the spark one. You would want to add the latest jar (gs://spark-lib/bigquery/spark-bigquery-latest.jar) to your notebook or to the cluster

**Comment by vliao-semios** [comment]
Okay, now it works with:

```
gcloud beta dataproc clusters create test-cluster \
    --project $PROJECT_NAME \
    --enable-component-gateway \
    --optional-components=ANACONDA,JUPYTER \
    --bucket $BUCKET \
    --region us-west2 \
    --properties "spark:spark.jars=gs://spark-lib/bigquery/spark-bigquery-latest.jar" \
    --single-node
```

And in the notebook just write:


```
from pyspark.sql import SparkSession
spark = SparkSession.builder \
  .appName('Top Shakepeare words')\
  .getOrCreate()

df = spark.read \
  .format('bigquery') \
  .option('table', 'publicdata.samples.shakespeare') \
  .load()
```

`--properties` options can update the spark config, and it automatically downloads files from `gs://` uris.

**Comment by TracyWest** [comment]
I came across similar issue when working in Jupyter on Dataproc.

Below is the code i used for loading bigquery table into dataproc cluster

```
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName('Jupyter BigQuery Storage').config('spark.jars','gs://spark-lib/bigquery/spark-bigquery-latest.jar').getOrCreate()

table = "publicdata.samples.shakespeare"
df = spark.read.format("com.google.cloud.spark.bigquery").option("table",table).load()
df.printSchema()
```

Below is the error i got

```
Py4JJavaErrorTraceback (most recent call last)
<ipython-input-17-789ad67053e5> in <module>()
      1 table = "publicdata.samples.shakespeare"
----> 2 df = spark.read.format("com.google.cloud.spark.bigquery").option("table",table).load()
      3 df.printSchema()

/usr/lib/spark/python/pyspark/sql/readwriter.pyc in load(self, path, format, schema, **options)
    170             return self._df(self._jreader.load(self._spark._sc._jvm.PythonUtils.toSeq(path)))
    171         else:
--> 172             return self._df(self._jreader.load())
    173 
    174     @since(1.4)

/opt/conda/anaconda/lib/python2.7/site-packages/py4j/java_gateway.pyc in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/usr/lib/spark/python/pyspark/sql/utils.pyc in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/opt/conda/anaconda/lib/python2.7/site-packages/py4j/protocol.pyc in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o254.load.
: java.lang.ClassNotFoundException: Failed to find data source: com.google.cloud.spark.bigquery. Please find packages at http://spark.apache.org/third-party-projects.html
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:639)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:190)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:164)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.google.cloud.spark.bigquery.DefaultSource
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$23$$anonfun$apply$15.apply(DataSource.scala:622)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$23$$anonfun$apply$15.apply(DataSource.scala:622)
	at scala.util.Try$.apply(Try.scala:192)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$23.apply(DataSource.scala:622)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$23.apply(DataSource.scala:622)
	at scala.util.Try.orElse(Try.scala:84)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:622)
	... 13 more
```

**Comment by sk-haghighi** [comment]
> Okay, now it works with:
> 
> ```
> pyspark \     
>     --files <path-to-credential-file> \
>     --conf spark.executorEnv.GOOGLE_APPLICATION_CREDENTIALS=<name-of-credential-file> \
>     --conf spark.yarn.appMasterEnv.GOOGLE_APPLICATION_CREDENTIALS=<name-of-credential-file> \
>     --jars <path-to-bigquery-lib-jar> \
> ```
> 
> And in the code just:
> 
> ```
> spark.read.format("bigquery").option("table", "publicdata.samples.shakespeare").load()
> ```
> 
> Thanks a lot for your support!

Sorry Where we should run the following code? I am using pyspark in Databricks. and how from where I can find the path to the credential file and to path-to-bigquery-lib-jar?
> ```
> pyspark \     
>     --files <path-to-credential-file> \
>     --conf spark.executorEnv.GOOGLE_APPLICATION_CREDENTIALS=<name-of-credential-file> \
>     --conf spark.yarn.appMasterEnv.GOOGLE_APPLICATION_CREDENTIALS=<name-of-credential-file> \
>     --jars <path-to-bigquery-lib-jar> \
> ```

**Comment by davidrabinowitz** [comment]
This code should be run on the cluster's master node.

**Comment by sk-haghighi** [comment]
Thanks David for your reply. Cluster's master node on Databrick or google cloud? Sorry I am new in this area if you can attach a photo of the location it would be great. I actually want to run the following tutorial on web but I keep receiving the following error:
https://github.com/GoogleCloudDataproc/cloud-dataproc/blob/master/notebooks/python/1.1.%20BigQuery%20Storage%20%26%20Spark%20DataFrames%20-%20Python.ipynb
---------------------------------------------------Error------------------------------------------
java.lang.ClassNotFoundException: Failed to find data source: bigquery. Please find packages at http://spark.apache.org/third-party-projects.html

**Comment by radhika7983** [comment]
hello David, could you please help me with my error , My code is as below, I am trying to run this in Jupyter Notebbook created on data proc cluster

!scala -version
<Scala code runner version 2.11.12 -- Copyright 2002-2017, LAMP/EPFL>

from pyspark.sql import SparkSession
spark = SparkSession.builder \
  .appName('1.2. BigQuery Storage & Spark SQL - Python')\
  .config('spark.jars', 'gs://spark-lib/bigquery/spark-bigquery-latest_2.12.jar')\
  .config("viewsEnabled","true")\
  .getOrCreate()

spark.conf.set("spark.sql.repl.eagerEval.enabled",True)

df = spark.read \
  .format('bigquery') \
  .option('table', 'wmt-rdl-stage.dim_tables.store_dim') \
  .load()

I am getting error as below


---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-30-bcc65722cf80> in <module>
      1 df = spark.read \
      2   .format('bigquery') \
----> 3   .option('table', 'wmt-rdl-stage.dim_tables.store_dim') \
      4   .load()

/usr/lib/spark/python/pyspark/sql/readwriter.py in load(self, path, format, schema, **options)
    170             return self._df(self._jreader.load(self._spark._sc._jvm.PythonUtils.toSeq(path)))
    171         else:
--> 172             return self._df(self._jreader.load())
    173 
    174     @since(1.4)

/opt/conda/anaconda/lib/python3.6/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/usr/lib/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/opt/conda/anaconda/lib/python3.6/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o411.load.
: java.util.ServiceConfigurationError: org.apache.spark.sql.sources.DataSourceRegister: Provider com.google.cloud.spark.bigquery.BigQueryRelationProvider could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:43)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:247)
	at scala.collection.TraversableLike$class.filter(TraversableLike.scala:259)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:630)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:194)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:167)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.google.cloud.spark.bigquery.BigQueryUtilScala$
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.<init>(BigQueryRelationProvider.scala:42)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.<init>(BigQueryRelationProvider.scala:49)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 24 more

I followed your answer for the same error in stackoverflow https://stackoverflow.com/questions/64796397/pyspark-error-reading-bigquery-java-lang-classnotfoundexception-org-apache-spa
But I still get same error.

could you please help.
