### ISSUE TITLE
Get error GoogleHadoopFileSystem not found when upgrade to the latest lib

### ISSUE THREAD

**Issue by ruixuel** [GoogleCloudPlatform/spark-bigquery-connector#76]
Hi,

I got the following error after I upgraded to the latest lib: 
`Exception in thread "main" java.util.ServiceConfigurationError: org.apache.hadoop.fs.FileSystem: Provider com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem not found
    at java.util.ServiceLoader.fail(ServiceLoader.java:239)
    at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
    at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372)
    at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
    at java.util.ServiceLoader$1.next(ServiceLoader.java:480)`

I didn't get any error when I used the old version of lib (0.8.1-beta).

Could you help to solve this problem?
Thank you!

**Comment by davidrabinowitz** [comment]
I'm afraid that before version 0.9.0-beta the library had no dependency on the gcs-connector, nor write to BigQuery support.
If you want to use this feature or otherwise write data to GCS using other spark APIs such as rdd.saveAsTextFile("gs://...") or df.write.parquet("gs://...) then please configure the gcs-connector as explained [here](https://github.com/GoogleCloudPlatform/bigdata-interop/tree/master/gcs).
