### ISSUE TITLE
GoogleJsonResponseException: 401 Unauthorized

### ISSUE THREAD

**Issue by megancooper** [GoogleCloudPlatform/spark-bigquery-connector#91]
I am trying to save a dataframe from a spark job running on an AWS EMR cluster to BigQuery, but am recieving a `401`. What is wrong with my spark code? Could it be my service does not have overwrite permissions? This service has the role `BigQuery Admin`

Also, it would be nicer if we could supply an object directly inside the `option` configurations instead of `base64` or a json file. I am having trouble using the JSON file while my cluster is running because files are not the same across driver and worker nodes. [base64 is also not working for me due to some unknown encoding issue...](https://stackoverflow.com/questions/59258549/spark-bigquery-connector-baseencodingdecodingexception-unrecognized-character). Being able to directly set these variables would make creating an EMR/Spark + BigQuery workload alot easier. Thank you for any and all help.

credentials.json format
```
{
  "type": "service_account",
  "project_id": "<MY_PROJECT_NAME>",
  "private_key_id": "<PRIVATE_KEY_ID>",
  "private_key": "-----BEGIN PRIVATE KEY-----<LONG LIST OF CHARS>-----END PRIVATE KEY-----\n",
  "client_email": "service@project.iam.gserviceaccount.com",
  "client_id": "<CLIENT_ID>",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/<service>%40<project>.iam.gserviceaccount.com"
}
```

Spark Script
```
SPARK_CONTEXT.addFile("/home/hadoop/credentials.json")
SPARK_CONTEXT._jsc \
    .hadoopConfiguration() \
    .set("fs.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem")
SPARK_CONTEXT._jsc \
    .hadoopConfiguration() \
    .set("fs.AbstractFileSystem.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS")
SPARK_CONTEXT._jsc \
    .hadoopConfiguration() \
    .set("fs.gs.project.id", "<MY_GCLOUD_PROJECT_ID>")
SPARK_CONTEXT._jsc \
    .hadoopConfiguration() \
    .set("google.cloud.auth.service.account.json.keyfile", SparkFiles.get("credentials.json"))


def main():
    #  ... init dataframe ...
    df \
        .write \
        .format("bigquery") \
        .option("temporaryGcsBucket", "emr_spark") \
        .option("project", "<MY_GCLOUD_PROJECT_ID>") \
        .option("parentProject", "<MY_GCLOUD_PROJECT_ID>") \
        .option("table", "<MY_GCLOUD_PROJECT_ID>:dataset.table") \
        .mode("overwrite") \
        .save()
    return

```

Error:
```
19/12/10 18:25:33 INFO CodecConfig: Compression: SNAPPY
19/12/10 18:25:33 INFO CodecConfig: Compression: SNAPPY
19/12/10 18:25:33 INFO ParquetOutputFormat: Parquet block size to 134217728
19/12/10 18:25:33 INFO ParquetOutputFormat: Parquet page size to 1048576
19/12/10 18:25:33 INFO ParquetOutputFormat: Parquet dictionary page size to 1048576
19/12/10 18:25:33 INFO ParquetOutputFormat: Dictionary is on
19/12/10 18:25:33 INFO ParquetOutputFormat: Validation is off
19/12/10 18:25:33 INFO ParquetOutputFormat: Writer version is: PARQUET_1_0
19/12/10 18:25:33 INFO ParquetOutputFormat: Maximum row group padding size is 8388608 bytes
19/12/10 18:25:33 INFO ParquetOutputFormat: Page size checking is: estimated
19/12/10 18:25:33 INFO ParquetOutputFormat: Min row count for page size check is: 100
19/12/10 18:25:33 INFO ParquetOutputFormat: Max row count for page size check is: 10000
19/12/10 18:25:34 INFO ParquetWriteSupport: Initialized Parquet WriteSupport with Catalyst schema:
{
  "type" : "struct",
  "fields" : [ {
    "name" : "id",
    "type" : "string",
    "nullable" : true,
    "metadata" : { }
  } ...(other fields)...]
}
and corresponding Parquet message type:
message spark_schema {
  optional binary id (UTF8);
  ...(other fields)...
}


19/12/10 18:25:34 INFO SparkHadoopMapRedUtil: No need to commit output of task because needsTaskCommit=false: attempt_20191210182527_0004_m_000048_108
19/12/10 18:25:34 INFO Executor: Finished task 48.0 in stage 4.0 (TID 108). 4769 bytes result sent to driver
19/12/10 18:25:34 INFO TaskSetManager: Finished task 48.0 in stage 4.0 (TID 108) in 255 ms on localhost (executor driver) (47/50)
19/12/10 18:25:34 INFO SparkHadoopMapRedUtil: No need to commit output of task because needsTaskCommit=false: attempt_20191210182527_0004_m_000049_109
19/12/10 18:25:34 INFO Executor: Finished task 49.0 in stage 4.0 (TID 109). 4769 bytes result sent to driver
19/12/10 18:25:34 INFO TaskSetManager: Finished task 49.0 in stage 4.0 (TID 109) in 243 ms on localhost (executor driver) (48/50)
19/12/10 18:25:34 INFO SparkHadoopMapRedUtil: No need to commit output of task because needsTaskCommit=false: attempt_20191210182527_0004_m_000027_110
19/12/10 18:25:34 INFO Executor: Finished task 27.0 in stage 4.0 (TID 110). 4769 bytes result sent to driver
19/12/10 18:25:34 INFO TaskSetManager: Finished task 27.0 in stage 4.0 (TID 110) in 247 ms on localhost (executor driver) (49/50)
19/12/10 18:25:34 INFO InternalParquetRecordWriter: Flushing mem columnStore to file. allocated memory: 9511
19/12/10 18:25:36 INFO FileOutputCommitter: Saved output of task 'attempt_20191210182527_0004_m_000039_111' to gs://emr_spark/.spark-bigquery-local-1576002318252-36378c2a-2355-4ecf-97ce-943287f00af4/_temporary/0/task_20191210182527_0004_m_000039
19/12/10 18:25:36 INFO SparkHadoopMapRedUtil: attempt_20191210182527_0004_m_000039_111: Committed
19/12/10 18:25:36 INFO Executor: Finished task 39.0 in stage 4.0 (TID 111). 4941 bytes result sent to driver
19/12/10 18:25:36 INFO TaskSetManager: Finished task 39.0 in stage 4.0 (TID 111) in 2836 ms on localhost (executor driver) (50/50)
19/12/10 18:25:36 INFO TaskSchedulerImpl: Removed TaskSet 4.0, whose tasks have all completed, from pool
19/12/10 18:25:36 INFO DAGScheduler: ResultStage 4 (save at BigQueryWriteHelper.scala:65) finished in 7.592 s
19/12/10 18:25:36 INFO DAGScheduler: Job 0 finished: save at BigQueryWriteHelper.scala:65, took 9.741856 s
19/12/10 18:25:41 INFO FileFormatWriter: Write Job 52a4641c-d06d-4adc-9a51-ce52fd17ef4c committed.
19/12/10 18:25:41 INFO FileFormatWriter: Finished processing stats for write job 52a4641c-d06d-4adc-9a51-ce52fd17ef4c.
Traceback (most recent call last):
  File "/home/hadoop/test.py", line 179, in <module>
    main()
  File "/home/hadoop/test.py", line 71, in main
    .mode("append") \
  File "/home/hadoop/conda/lib/python3.7/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 736, in save
  File "/home/hadoop/conda/lib/python3.7/site-packages/pyspark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/home/hadoop/conda/lib/python3.7/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/home/hadoop/conda/lib/python3.7/site-packages/pyspark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o138.save.
: java.lang.RuntimeException: Failed to write to BigQuery
	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.writeDataFrameToBigQuery(BigQueryWriteHelper.scala:60)
	at com.google.cloud.spark.bigquery.BigQueryInsertableRelation.insert(BigQueryInsertableRelation.scala:44)
	at com.google.cloud.spark.bigquery.BigQueryRelationProvider.createRelation(BigQueryRelationProvider.scala:83)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:80)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:80)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:78)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:73)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:676)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:285)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:271)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryException: 401 Unauthorized
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.translate(HttpBigQueryRpc.java:106)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.create(HttpBigQueryRpc.java:206)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryImpl$5.call(BigQueryImpl.java:319)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryImpl$5.call(BigQueryImpl.java:316)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:105)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.RetryHelper.run(RetryHelper.java:76)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:50)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryImpl.create(BigQueryImpl.java:315)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.BigQueryImpl.create(BigQueryImpl.java:290)
	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.loadDataToBigQuery(BigQueryWriteHelper.scala:90)
	at com.google.cloud.spark.bigquery.BigQueryWriteHelper.writeDataFrameToBigQuery(BigQueryWriteHelper.scala:66)
	... 33 more
Caused by: com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.json.GoogleJsonResponseException: 401 Unauthorized
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:150)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:443)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1092)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:541)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:474)
	at com.google.cloud.spark.bigquery.repackaged.com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:591)
	at com.google.cloud.spark.bigquery.repackaged.com.google.cloud.bigquery.spi.v2.HttpBigQueryRpc.create(HttpBigQueryRpc.java:204)
	... 42 more
```

**Comment by megancooper** [comment]
Closing because I discovered and resolved my base64 encoding issue.
