### ISSUE TITLE
Best way to authnenticate from AWS EMR?

### ISSUE THREAD

**Issue by megancooper** [GoogleCloudPlatform/spark-bigquery-connector#92]
I am attempting to run a spark script that saves a dataframe to BigQuery from an AWS EMR cluster. I am having a hard time using `credentials` and `credentialsFile` to authenticate however.

**Issue**
When I authenticate using `credentialsFile` I get a `FileNotFound` error. Currently I have my `credentials.json` file for my service stored in s3. When my cluster starts, I download the file from s3, and use `SPARK_CONTEXT.addFile("/home/hadoop/credentials.json")` to add the file (ideally) to the master and worker nodes. Afterwards I set `google.cloud.auth.service.account.json.keyfile` using `SparkFiles.get("credentials.json")` to get the file's path.

This is not working however. I am able to set the path, but when I run my job I see the following error. What is the best/easiest way to authenticate from an AWS EMR cluster. Nothing I've tried seems to work...[the encoding feature results in an encoding error](https://stackoverflow.com/questions/59258549/spark-bigquery-connector-baseencodingdecodingexception-unrecognized-character), and there is not way to directly supply the information from my credentials file manually into the `options` while calling `df.write`

```
Job aborted due to stage failure: Task 2 in stage 4.0 failed 4 times, most recent failure: Lost task 2.3 in stage 4.0 (TID 92, ip-172-31-9-151.us-west-2.compute.internal, executor 1): java.io.FileNotFoundException: /mnt/tmp/spark-c1e9683c-0c78-43ba-a0b6-0ba787e5b8e2/userFiles-bf45542e-d159-4969-9fec-149d3f59cf03/credentials.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.util.CredentialFactory.getCredentialFromJsonKeyFile(CredentialFactory.java:280)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.util.CredentialConfiguration.getCredential(CredentialConfiguration.java:126)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.getCredential(GoogleHadoopFileSystemBase.java:1508)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.createGcsFs(GoogleHadoopFileSystemBase.java:1593)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.configure(GoogleHadoopFileSystemBase.java:1554)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.initialize(GoogleHadoopFileSystemBase.java:553)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystemBase.initialize(GoogleHadoopFileSystemBase.java:506)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2859)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:99)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2896)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2878)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:392)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:356)
	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.<init>(FileOutputCommitter.java:123)
	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.<init>(FileOutputCommitter.java:103)
	at org.apache.parquet.hadoop.ParquetOutputCommitter.<init>(ParquetOutputCommitter.java:43)
	at org.apache.parquet.hadoop.ParquetOutputFormat.getOutputCommitter(ParquetOutputFormat.java:442)
	at org.apache.spark.internal.io.HadoopMapReduceCommitProtocol.setupCommitter(HadoopMapReduceCommitProtocol.scala:100)
	at org.apache.spark.sql.execution.datasources.SQLHadoopMapReduceCommitProtocol.setupCommitter(SQLHadoopMapReduceCommitProtocol.scala:40)
	at org.apache.spark.internal.io.HadoopMapReduceCommitProtocol.setupTask(HadoopMapReduceCommitProtocol.scala:217)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:229)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:170)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:169)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
```

**Comment by megancooper** [comment]
Closing because I discovered and resolved my base64 encoding issue.

**Comment by seonghean** [comment]
@megancooper do you mind to share your code here ? I also look for the same things.

**Comment by megancooper** [comment]
@seonghean Sure! Apologies I think I didn't post the full solution because it was a bit involved. Essentially I created a bootstrap script for the AWS EMR cluster (shown below) that installs `google cloud` on the cluster and then sets the default project to the cloud project that the Big Query table falls under. I added my google cloud json file (`gcloud.json`) to an s3 bucket which is downloaded during the script so I can authenticate with google cloud. That file is also below under the EMR bootstrap script

**The Full Set of Steps**
1. Create a google cloud service account & json file ([by following their steps](https://cloud.google.com/docs/authentication/getting-started)) and uploading it to a folder in s3
2. [Create a Big Query s3 transfer job](https://cloud.google.com/bigquery-transfer/docs/s3-transfer)
3. Install google cloud (`gcloud`) on the cluster and authenticate & set the default project  using a shell script during the [bootstrap process of the AWS EMR cluster](https://docs.aws.amazon.com/emr/latest/ManagementGuide/emr-plan-bootstrap.html)
4. During the EMR pyspark script, upload/save the dataframe to s3 (as `*.csv`) and then use the `bigquery_datatransfer` python package to trigger the job. Be sure to use a delay so we can be sure the updated data frame is actually uploaded to s3 when the transfer job actually starts

**gcloud_bootstrap.sh**
Some Notes:
- (Replace `<project_id>` with your google cloud project name.)
- I noticed when copying over `gcloud.json` it copied over the folder the file was in to `/home/hadoop`. You may have to check this path after downloaded it from s3 to the cluster

```
#!/usr/bin/env bash

# download gcloud sdk
curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-272.0.0-linux-x86_64.tar.gz
tar zxvf google-cloud-sdk-272.0.0-linux-x86_64.tar.gz google-cloud-sdk

# configure python for gcloud
sudo ln -s /usr/local/bin/python2.7 /usr/local/bin/python2
export CLOUDSDK_PYTHON="/usr/bin/python2.7"

# install gcloud sdk
./google-cloud-sdk/install.sh --usage-reporting N --command-completion Y --path-update Y
source ./google-cloud-sdk/path.bash.inc
source ./google-cloud-sdk/completion.bash.inc

# download gcloud credentials file
aws s3 cp s3://path/to/gcloud.json /home/hadoop/

# create new configuration
# gcloud config configurations create default
gcloud config set project <project_id>
gcloud auth activate-service-account --key-file /home/hadoop/gcloud.json
export GOOGLE_APPLICATION_CREDENTIALS="/home/hadoop/gcloud.json"
```

gcloud.json (What I can share at least)
```
{
  "type": "service_account",
  "project_id": "<project_id>",
  "private_key_id": "<private_key_id>",
  "private_key": "-----BEGIN PRIVATE KEY-----\nSOME REALLY LONG PRIVATE KEY=\n-----END PRIVATE KEY-----\n",
  "client_email": "<client_name>@<project_id>.iam.gserviceaccount.com",
  "client_id": "<client_id>",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/<client_name>%40<project_id>.iam.gserviceaccount.com"
}
```

After the bootstrap script completes and the cluster actually runs, I save the spark dataframe Big Query by triggering a job as shown below in a the following pyspark script:

```
from pyspark import SparkContext
from utils.spark import get_spark_env
from pyspark.sql import SQLContext
from datetime import date
from google.cloud import bigquery_datatransfer
import pyspark.sql.functions as f
import pandas as pd
import pandas_gbq
import time

SPARK_CONTEXT = SparkContext(appName="Update Big Query Cache")
SPARK_ENV = get_spark_env(SPARK_CONTEXT)
SQL_CONTEXT = SQLContext(SPARK_CONTEXT)
GCLOUD_CRED_PATH = "/home/hadoop/gcloud.json" # gcloud.json used
SPARK_CONTEXT.addFile(GCLOUD_CRED_PATH)

SPARK_CONTEXT._jsc \
    .hadoopConfiguration() \
    .set("fs.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem")
SPARK_CONTEXT._jsc \
    .hadoopConfiguration() \
    .set("fs.AbstractFileSystem.gs.impl", "com.google.cloud.hadoop.fs.gcs.GoogleHadoopFS")
SPARK_CONTEXT._jsc \
    .hadoopConfiguration() \
    .set("fs.gs.project.id", "fluted-bit-261215")
SPARK_CONTEXT._jsc \
    .hadoopConfiguration() \
    .set("google.cloud.auth.service.account.json.keyfile", GCLOUD_CRED_PATH)
    
def main():
    # clear current bigquery table row
    pandas_gbq.read_gbq(
        "delete from schema.table where id != ''",
        private_key=GCLOUD_CRED_PATH,
        project_id="<project_id>",
        dialect='standard',
        verbose=False)

  # create spark df however you do ...
  df = creating_spark_df()
  
  # safe dataframe to s3
  df.select(['columns', 'to', 'keep']) \
    .write \
        .mode("overwrite") \
        .save("s3a://s3/path/to/save/", format='csv', header=False)
        
   # trigger bigquery data transfer service
    client = bigquery_datatransfer.DataTransferServiceClient()
    project_id = 'numeric_only_project_id'
    transfer_config_id = '4502dfc1-09f5-4b08-a796-e8722149e28a'  # alphanumeric UUID you'll find in the google cloud UI for the transfer job
    parent = client.project_transfer_config_path(project_id, transfer_config_id)
    # add 15 minutes before starting transfer job to avoid starting before write is finished
    start_time = bigquery_datatransfer.types.Timestamp(seconds=int(time.time() + (60 * 15)))
    response = client.start_manual_transfer_runs(parent, requested_run_time=start_time)
```

Hope this helps, definitely was a journey to get here haha!

**Comment by seonghean** [comment]
@megancooper thanks a lot. I have been struggle for this quite sometimes.  Info on the internet quite limited. Let me try this out.
